# cSpell:ignore checkmake hadolint autofix autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://git.schmidl.dev/schtobia/woodpecker-lint
    rev: 1.0.0
    hooks:
      - id: woodpecker-lint
  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks [CI SKIP]

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  # NB: hadolint not included in pre-commit.ci
  skip: [check-hooks-apply, check-useless-excludes, hadolint, prettier]
  submodules: false
