FROM --platform=$BUILDPLATFORM docker.io/golang:1.21 AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH CI_COMMIT_SHA CI_COMMIT_TAG CI_COMMIT_BRANCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    make build-agent
RUN mkdir -p /etc/echoes/agent

FROM scratch
ENV GODEBUG=netdns=go
EXPOSE 3000

# copy agent binary
COPY --from=build /src/dist/echoes-agent /bin/
COPY --from=build /etc/echoes/agent /etc

ENTRYPOINT ["/bin/echoes-agent"]