variables:
  - &node_image "docker.io/node:18-alpine"
  - path: &when_path
      - "docs/**"
      - ".woodpecker/.docs.yml"
      - "backend/**"
  - path: &docker_path # web source code
      - "frontend/**"
      - "backend/**"
      # go source code
      - "**/*.go"
      - "go.*"
      # Dockerfile changes
      - "docker/**"

when:
  - event: tag
  - event: pull_request
  - event: push
    path:
      - <<: *when_path
      - <<: *docker_path
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
  - event: pull_request_closed
    path: *when_path
  - event: manual
    evaluate: 'TASK == "docs"'

steps:
  build-deploy:
    image: *node_image
    directory: docs/
    secrets: [git_user, git_password, git_user_email, git_user_name]
    commands:
      - apk add openssh-client rsync git
      - npm install --frozen-lockfile
      - GIT_USER="$${GIT_USER}" GIT_PASSWORD="$${GIT_PASSWORD}" GIT_USER_EMAIL="$${GIT_USER_EMAIL}" GIT_USER_NAME="$${GIT_USER_NAME}" npm run deploy
    when:
      - event: push
        path:
          - <<: *when_path
          - <<: *docker_path
        branch: ${CI_REPO_DEFAULT_BRANCH}
      - event: [manual, tag]
