when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

# Only run on amd64 agents
labels:
  arch: amd64

variables:
  - &golang_image "docker.io/golang:1.21.6"
  - &buildx_plugin "docker.io/woodpeckerci/plugin-docker-buildx:2.3.0"
  - &platforms_release "linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64,linux/ppc64le,linux/riscv64,linux/s390x,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64"
  - &platforms_preview "linux/amd64"
  - &platforms_server "linux/amd64"
  - &build_args "CI_COMMIT_SHA=${CI_COMMIT_SHA},CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH},CI_COMMIT_TAG=${CI_COMMIT_TAG}"

  # vars used on push / tag events only
  - publish_logins: &publish_logins # Default DockerHub login
      - registry: https://index.docker.io/v1/
        username: "vmgware"
        password:
          from_secret: docker_password
      - registry: https://harbor.vmgware.dev
        username: "robot$vmgware"
        password:
          from_secret: harbor_password
  - &publish_repos_agent "vmgware/echoes-agent,harbor.vmgware.dev/echoes/agent"
  - &publish_repos_server "vmgware/echoes-server,harbor.vmgware.dev/echoes/server"
  - path: &when_path # web source code
      - "web/**"
      # api source code
      - "server/**"
      # go source code
      - "**/*.go"
      - "go.*"
      # Dockerfile changes
      - "docker/**"
      # pipeline config changes
      - ".woodpecker/.docker.yml"

steps:
  vendor:
    image: *golang_image
    pull: true
    commands:
      - go mod vendor
    when:
      - event: pull_request
        evaluate: 'CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images"'
      - event: pull_request
        path: *when_path
      - branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        event: [push, tag]
        path: *when_path

  ###############
  # S e r v e r #
  ###############

  publish-server-preview:
    image: *buildx_plugin
    settings:
      repo: *publish_repos_server
      dockerfile: docker/Dockerfile.server
      platforms: *platforms_preview
      tag: pull_${CI_COMMIT_PULL_REQUEST}
      build_args: *build_args
      logins: *publish_logins
    when:
      evaluate: 'CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images"'
      event: pull_request

  publish-next-server:
    image: *buildx_plugin
    settings:
      repo: *publish_repos_server
      dockerfile: docker/Dockerfile.server
      platforms: *platforms_server
      tag: [next, "next-${CI_COMMIT_SHA:0:10}"]
      logins: *publish_logins
      build_args: *build_args
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
      path: *when_path

  release-server:
    image: *buildx_plugin
    settings:
      repo: *publish_repos_server
      dockerfile: docker/Dockerfile.server
      platforms: *platforms_server
      # remove 'latest' on older version branches to avoid accidental downgrade
      tag: [latest, "${CI_COMMIT_TAG}"]
      logins: *publish_logins
      build_args: *build_args
    when:
      event: tag

  #############
  # A g e n t #
  #############

  publish-agent-preview:
    depends_on:
      - vendor
    image: *buildx_plugin
    settings:
      repo: *publish_repos_agent
      dockerfile: docker/Dockerfile.agent
      platforms: *platforms_preview
      tag: pull_${CI_COMMIT_PULL_REQUEST}
      build_args: *build_args
      logins: *publish_logins
    when:
      evaluate: 'CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images"'
      event: pull_request

  build-agent:
    depends_on:
      - vendor
    image: *buildx_plugin
    settings:
      dry_run: true
      repo: *publish_repos_agent
      dockerfile: docker/Dockerfile.agent
      platforms: *platforms_preview
      tag: pull_${CI_COMMIT_PULL_REQUEST}
      build_args: *build_args
    when:
      evaluate: 'not (CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images")'
      event: pull_request
      path: *when_path

  publish-next-agent:
    depends_on:
      - vendor
    image: *buildx_plugin
    settings:
      repo: *publish_repos_agent
      dockerfile: docker/Dockerfile.agent
      platforms: *platforms_release
      tag: [next, "next-${CI_COMMIT_SHA:0:10}"]
      logins: *publish_logins
      build_args: *build_args
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
      path: *when_path

  release-agent:
    depends_on:
      - vendor
    image: *buildx_plugin
    settings:
      repo: *publish_repos_agent
      dockerfile: docker/Dockerfile.agent
      platforms: *platforms_release
      # remove 'latest' on older version branches to avoid accidental downgrade
      tag: [latest, "${CI_COMMIT_TAG}"]
      logins: *publish_logins
      build_args: *build_args
    when:
      event: tag
