variables:
  - &node_image "docker.io/node:18-alpine"
  - path: &when_path
      - "docs/**"
      - ".woodpecker/.docs.yml"
      - "backend/**"
  - path: &docker_path # web source code
      - "frontend/**"
      - "backend/**"
      # go source code
      - "**/*.go"
      - "go.*"
      # Dockerfile changes
      - "docker/**"

when:
  - event: tag
  - event: pull_request
  - event: push
    path:
      - <<: *when_path
      - <<: *docker_path
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
  - event: pull_request_closed
    path: *when_path
  - event: manual
    evaluate: 'TASK == "docs"'

steps:
  build:
    image: *node_image
    directory: docs/
    commands:
      - npm install --frozen-lockfile
      - npm run build
    when:
      - path: *when_path
        event: [tag, pull_request, push]
      - event: manual

  deploy:
    image: *node_image
    secrets: [github_private_key]
    commands:
      - apk add openssh-client rsync git
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$GITHUB_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
      - chmod 0600 $HOME/.ssh/id_rsa
      - cd docs
      - USE_SSH=true npm run deploy
    when:
      - event: push
        path:
          - <<: *when_path
          - <<: *docker_path
        branch: ${CI_REPO_DEFAULT_BRANCH}
      - event: [manual, tag]
