when:
  - event: [pull_request, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &trivy_image aquasec/trivy:0.46.1
  - &trivy_plugin woodpeckerci/plugin-trivy:1.0.1

steps:
  server:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir: server/

  docs:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir: docs/

  web:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir: web/
