when:
  event: [push]
  branch: master
  path:
    exclude: [README.md, LICENSE, .github, .gitignore]
    include: [server/**, core/**, web/**, agent/**]

# Only run on amd64 agents
labels:
  arch: amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      lfs: true
      partial: false
      depth: 0

steps:
  # TODO: Should be ran after all tests are done and still run even if tests fail
  SonarQube Scan:
    image: sonarsource/sonar-scanner-cli:latest
    secrets: [sonar_token]
    environment:
      SONAR_TOKEN: $SONAR_TOKEN
    commands:
      - sonar-scanner
