when:
  - event: pull_request
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &node_image 'docker.io/node:18-alpine'
  - &when
    path:
      # related config files
      - '.woodpecker/.web.yml'
      # web source code
      - 'web/**'
      # server source code
      - 'server/**'

steps:
  install-dependencies:
    image: *node_image
    directory: web/
    commands:
      - npm install --frozen-lockfile
    when: *when

  lint:
    depends_on:
      - install-dependencies
    image: *node_image
    directory: web/
    commands:
      - npm run lint
    when: *when
